/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MiraiGeneralView } from "./MiraiGeneralView";
export type { MiraiSimpleLens } from "./MiraiSimpleLens";
